### ISSUE TITLE
Convert to "import .. from fluent-dom"?

### ISSUE THREAD

**Issue by pdehaan** [projectfluent/fluent-web#3]
https://github.com/projectfluent/fluent-web/blob/4458ff04c0c3a300ac81ae8868dc32bb07a5db11/src/index.js#L5

I think that should just be:

```js
import { DOMLocalization } from "fluent-dom";
```

From the looks of it, the current version leaks outside of the git repo into a parent folder looking for files (which fails for me locally because I don't have a fluent.js folder or fluent-dom cloned).

**Comment by zbraniecki** [comment]
That was fixed in #1
