### ISSUE TITLE
More README instructions on how to use Make

### ISSUE THREAD

**Issue by pdehaan** [projectfluent/fluent-web#4]
I'm struggling w/ the Make commands, and I think it's assuming that I have some globally installed modules.

In order to get <kbd>$ make build</kbd> to build locally, I had to do some tweaking and install **rollup** locally as a devDep:

```diff
diff --git a/makefile b/makefile
index 52847af..a125590 100644
--- a/makefile
+++ b/makefile
@@ -6,7 +6,7 @@ include ./common.mk
 build: $(PACKAGE).js

 $(PACKAGE).js: $(SOURCES)
-       @rollup $(CURDIR)/src/index.js \
+       ./node_modules/.bin/rollup $(CURDIR)/src/index.js \
                --config $(CURDIR)/rollup_config.js \
                --banner "/* $(PACKAGE)@$(VERSION) */" \
                --name $(GLOBAL) \
(END)
```

**Comment by zbraniecki** [comment]
Thanks! Fixed in https://github.com/projectfluent/fluent-web/commit/454667ac03590579e678c2c52875d72e37d26e62
